import { Theme } from '../types';

export const THEMES: Record<string, Theme> = {
  RETRO_ARCADE: {
    id: 'RETRO_ARCADE',
    name: 'Retro Arcade',
    bgClass: 'bg-zinc-950 text-white border-zinc-800',
    boardBgClass: 'bg-zinc-900 border-zinc-800 border-2 shadow-[0_0_15px_rgba(0,0,0,0.5)]',
    snakeHeadClass: 'bg-emerald-400 rounded-sm border border-emerald-300 shadow-[0_0_8px_#34d399]',
    snakeBodyClass: 'bg-emerald-500 rounded-md border border-emerald-400 shadow-[0_0_4px_#10b981]',
    foodClass: 'bg-rose-500 rounded-full animate-pulse shadow-[0_0_10px_#f43f5e]',
    specialFoodClass: 'bg-amber-400 rounded-full animate-bounce shadow-[0_0_15px_#fbbf24] border border-white',
    wallClass: 'bg-zinc-700 border border-zinc-600 shadow-inner',
    portalClass: 'bg-indigo-500 rounded-full border-2 border-cyan-400 shadow-[0_0_12px_#6366f1] animate-pulse',
    accentTextClass: 'text-emerald-400 font-mono tracking-wider',
    fontFamily: 'font-mono',
    buttonStyle: 'bg-zinc-800 hover:bg-zinc-700 active:bg-emerald-500 active:text-zinc-950 border border-zinc-700 hover:border-emerald-500 text-zinc-100 transition-all font-mono',
  },
  NOKIA_CLASSIC: {
    id: 'NOKIA_CLASSIC',
    name: 'Nokia 3310',
    bgClass: 'bg-[#c2ccb3] text-[#1c2415] border-[#9fab8c]',
    boardBgClass: 'bg-[#c9d4ba] border-4 border-[#1c2415] p-1 shadow-inner',
    snakeHeadClass: 'bg-[#1c2415] rounded-none border border-[#c9d4ba]',
    snakeBodyClass: 'bg-[#1c2415] rounded-none border border-[#c9d4ba]/40',
    foodClass: 'bg-[#1c2415] rounded-none p-0.5 border border-[#c9d4ba]',
    specialFoodClass: 'bg-[#1c2415] rounded-none border-2 border-dashed border-[#c9d4ba] animate-pulse',
    wallClass: 'bg-[#1c2415] opacity-90',
    portalClass: 'bg-transparent border-2 border-double border-[#1c2415] animate-pulse',
    accentTextClass: 'text-[#1c2415] font-bold font-mono',
    fontFamily: 'font-mono uppercase',
    buttonStyle: 'bg-[#c9d4ba] border-2 border-[#1c2415] text-[#1c2415] hover:bg-[#1c2415] hover:text-[#c9d4ba] font-bold transition-colors font-mono',
  },
  CYBERPUNK: {
    id: 'CYBERPUNK',
    name: 'Cyberpunk',
    bgClass: 'bg-slate-950 text-yellow-400 border-yellow-500/20',
    boardBgClass: 'bg-slate-900 border-2 border-cyan-500 shadow-[0_0_15px_rgba(6,182,212,0.15)]',
    snakeHeadClass: 'bg-cyan-400 rounded-tr-lg rounded-bl-lg border border-white shadow-[0_0_10px_#22d3ee]',
    snakeBodyClass: 'bg-cyan-500 rounded-sm border border-cyan-400 shadow-[0_0_5px_#06b6d4]',
    foodClass: 'bg-fuchsia-500 rounded-none transform rotate-45 border border-white shadow-[0_0_12px_#d946ef]',
    specialFoodClass: 'bg-yellow-400 rounded-none transform rotate-45 border-2 border-fuchsia-500 animate-bounce shadow-[0_0_15px_#eab308]',
    wallClass: 'bg-slate-800 border-t-2 border-yellow-500 shadow-[0_0_6px_rgba(234,179,8,0.2)]',
    portalClass: 'bg-purple-600 rounded-full border-2 border-yellow-400 shadow-[0_0_14px_#a855f7] animate-ping',
    accentTextClass: 'text-cyan-400 font-mono italic',
    fontFamily: 'font-mono',
    buttonStyle: 'bg-slate-900 border border-yellow-500/50 hover:border-cyan-400 text-yellow-400 hover:text-cyan-400 font-bold transition-all',
  },
  JUNGLE: {
    id: 'JUNGLE',
    name: 'Jungle Safari',
    bgClass: 'bg-emerald-950 text-amber-100 border-emerald-900',
    boardBgClass: 'bg-stone-900 border-4 border-emerald-800 shadow-md',
    snakeHeadClass: 'bg-lime-500 rounded-full border border-lime-300',
    snakeBodyClass: 'bg-emerald-600 rounded-full border border-emerald-500',
    foodClass: 'bg-red-500 rounded-full shadow-sm',
    specialFoodClass: 'bg-amber-500 rounded-full border border-white animate-bounce',
    wallClass: 'bg-stone-700 border-2 border-stone-600 rounded-sm',
    portalClass: 'bg-teal-600 rounded-full border border-stone-100 animate-pulse',
    accentTextClass: 'text-lime-400 font-semibold font-sans',
    fontFamily: 'font-sans',
    buttonStyle: 'bg-emerald-900/60 hover:bg-emerald-800/80 active:bg-lime-600 active:text-stone-950 text-amber-50 shadow-sm transition-colors border border-emerald-800',
  },
  JUNGLE_NIGHT: {
    id: 'JUNGLE_NIGHT',
    name: 'Jungle Night 🌙',
    bgClass: 'bg-violet-950 text-indigo-100 border-violet-900',
    boardBgClass: 'bg-slate-950 border-4 border-indigo-900 shadow-lg',
    snakeHeadClass: 'bg-teal-400 rounded-full border border-teal-200 shadow-[0_0_8px_rgba(45,212,191,0.6)]',
    snakeBodyClass: 'bg-indigo-600 rounded-full border border-indigo-500 shadow-[0_0_4px_rgba(79,70,229,0.4)]',
    foodClass: 'bg-yellow-400 rounded-full shadow-[0_0_10px_rgba(234,179,8,0.8)] animate-pulse',
    specialFoodClass: 'bg-fuchsia-400 rounded-full border border-white animate-bounce shadow-[0_0_15px_rgba(244,63,94,1)]',
    wallClass: 'bg-indigo-950 border-2 border-violet-800 rounded-sm',
    portalClass: 'bg-emerald-500 rounded-full border-2 border-white animate-ping',
    accentTextClass: 'text-teal-400 font-bold font-sans tracking-wide',
    fontFamily: 'font-sans',
    buttonStyle: 'bg-indigo-950/60 hover:bg-indigo-900/80 active:bg-teal-400 active:text-stone-950 text-indigo-50 shadow-sm transition-colors border border-indigo-800',
  },
  CANDY: {
    id: 'CANDY',
    name: 'Sweet Candy 🍬',
    bgClass: 'bg-pink-50 text-fuchsia-900 border-pink-200',
    boardBgClass: 'bg-white border-4 border-pink-300 shadow-lg rounded-2xl',
    snakeHeadClass: 'bg-purple-400 rounded-xl border-2 border-white shadow-sm',
    snakeBodyClass: 'bg-pink-400 rounded-xl border border-pink-300 shadow-sm',
    foodClass: 'bg-rose-500 rounded-full shadow-sm animate-pulse',
    specialFoodClass: 'bg-amber-400 rounded-full border-2 border-rose-400 animate-bounce',
    wallClass: 'bg-indigo-300 border-2 border-indigo-200 rounded-md',
    portalClass: 'bg-sky-400 rounded-full border-2 border-pink-200 animate-pulse',
    accentTextClass: 'text-rose-500 font-bold font-sans',
    fontFamily: 'font-sans',
    buttonStyle: 'bg-white hover:bg-pink-100 active:bg-rose-400 active:text-white border-2 border-pink-300 text-fuchsia-800 font-semibold shadow-sm rounded-xl transition-colors',
  },
  CANDY_MINT: {
    id: 'CANDY_MINT',
    name: 'Chco Mint Candy 🍫',
    bgClass: 'bg-teal-50 text-emerald-950 border-teal-200',
    boardBgClass: 'bg-stone-50 border-4 border-teal-300 shadow-lg rounded-2xl',
    snakeHeadClass: 'bg-emerald-400 rounded-xl border-2 border-stone-800 shadow-sm',
    snakeBodyClass: 'bg-amber-900 rounded-xl border border-amber-950 shadow-sm',
    foodClass: 'bg-teal-500 rounded-full shadow-sm animate-bounce',
    specialFoodClass: 'bg-rose-400 rounded-full border-2 border-white animate-pulse',
    wallClass: 'bg-amber-800 border-2 border-amber-900 rounded-md',
    portalClass: 'bg-emerald-400 rounded-full border-2 border-teal-200 animate-pulse',
    accentTextClass: 'text-teal-600 font-black font-mono',
    fontFamily: 'font-mono',
    buttonStyle: 'bg-white hover:bg-teal-100 active:bg-emerald-500 active:text-white border-2 border-teal-200 text-emerald-900 font-semibold shadow-sm rounded-xl transition-colors',
  },
  CANDY_LEMON: {
    id: 'CANDY_LEMON',
    name: 'Sour Lemon drop 🍋',
    bgClass: 'bg-amber-50 text-amber-950 border-amber-200',
    boardBgClass: 'bg-white border-4 border-amber-300 shadow-lg rounded-2xl',
    snakeHeadClass: 'bg-yellow-400 rounded-xl border-2 border-white shadow-sm',
    snakeBodyClass: 'bg-sky-400 rounded-xl border border-sky-300 shadow-sm',
    foodClass: 'bg-yellow-500 rounded-full shadow-sm animate-pulse',
    specialFoodClass: 'bg-lime-400 rounded-full border-2 border-white animate-bounce',
    wallClass: 'bg-amber-400 border-2 border-amber-500 rounded-md',
    portalClass: 'bg-purple-400 rounded-full border-2 border-pink-200 animate-pulse',
    accentTextClass: 'text-amber-600 font-black font-sans',
    fontFamily: 'font-sans',
    buttonStyle: 'bg-white hover:bg-amber-100 active:bg-yellow-400 active:text-zinc-900 border-2 border-amber-200 text-amber-900 font-semibold shadow-sm rounded-xl transition-colors',
  }
};
